export default {
  pages: [
    'pages/login/index',
    'pages/main/index',
    'pages/indexHome/index',
    'pages/addHome/index',
    'pages/postHome/index',
    'pages/mineHome/index',
  ],
  subpackages: [
    {
      root: 'subpackage',
      pages: [
        'actComment/index',
        'addIntroduce/index',
        'myNotification/index',
        'postDetail/index',
        'postAdd/index',
        'userProfile/index',
        'actScreen/index',
        'addLabel/index',
        'addSuccess/index',
        'review/index',
        'addPeopleIndex/index',
        'addPeoplePage/index',
        'album/index',
        'mySearch/index',
      ],
    },
  ],
  window: {
    navigationStyle: 'custom',
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#F9F8FC',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black',
    backgroundColor: '#F9F8FC',
  },
  tabBar: {
    custom: true,
    color: '#C8C8C8',
    selectedColor: '#BE7CE0',
    backgroundColor: '#fff',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/main/index',
        text: '主页',
      },
      {
        pagePath: 'pages/indexHome/index',
        text: '首页',
        iconPath: 'common/assets/tabBar/img/home.png',
        selectedIconPath: 'common/assets/tabBar/img-active/home-active.png',
      },
      {
        pagePath: 'pages/addHome/index',
        text: '添加',
        iconPath: 'common/assets/tabBar/img/add.png',
        selectedIconPath: 'common/assets/tabBar/img-active/add-active.png',
      },
      {
        pagePath: 'pages/postHome/index',
        text: '发现',
        iconPath: 'common/assets/tabBar/img/blog.png',
        selectedIconPath: 'common/assets/tabBar/img-active/blog-active.png',
      },
      {
        pagePath: 'pages/mineHome/index',
        text: '我的',
        iconPath: 'common/assets/tabBar/img/mine.png',
        selectedIconPath: 'common/assets/tabBar/img-active/mine-active.png',
      },
    ],
  },
};
